ROOT: '/data1/xjheng/dataset/ILSVRC2012/'
DATA: 'ILSVRC2012'
FDIM: 2048+1024
INPUT_SIZE: 256
INPUT_SIZE_480: 480
CROP_SIZE: 224
CROP_SIZE_448: 448
RESUME: ''
DEBUG: 'debug'
LOG_DIR: 'log/'
NUM_THRESHOLD: 20
C_BASE: 64
WORKERS: 8
EPOCHS: 5
BATCH_SIZE: 256
LR: 0.0001
WEIGHT_DECAY: 0.0001
MOMENTUM: 0.9
PRINT_FREQ: 250
NUM_CLASSES: 1000
SEED: 1
EXPERIMENT: ''
PRETRAINED: 'mocov2'
