ROOT: '/data1/xjheng/dataset/cub-200-2011/CUB_200_2011/'
DATA: 'CUB_200_2011'
DEPTH: 50
FDIM: 2048+1024
RESUME: ''
DEBUG: 'debug'
LOG_DIR: 'log/'
NUM_THRESHOLD: 20
WORKERS: 4
EPOCHS: 20
BATCH_SIZE: 16
LR: 0.0001
WEIGHT_DECAY: 0.0001
MOMENTUM: 0.9
PRINT_FREQ: 25
SEED: 1
EXPERIMENT: ''
EVALUTATE: False
PRETRAINED: 'mocov2'